### ISSUE TITLE
Problem with Travis CI unit testing

### ISSUE THREAD

**Issue by jabranr** [jabranr/lassi#6]
There seems to be a problem with Travis CI while running unit tests. The environment cannot properly use the `autoloader` and returns error with `Lassi\App\Util` class not found. Currently tests are only available in `dev-master` branch.

For more details, please see build history at Travis CI at https://travis-ci.org/jabranr/lassi/builds

**Comment by 3even** [comment]
Having the same issue. Can't even get the basic examples working.

**Comment by jabranr** [comment]
@3even Yes, I figured that it is down to Mac being case-insensitive OS. Renaming the directories according to their namespaces fixes the problem.
